### PR TITLE
fix: support rendering number array

### LINKED ISSUE #333: Error: Invalid `value` of type `number` supplied to Option, expected `string` when `tags/combobox` is `true`
Error: Invalid `value` of type `number` supplied to Option, expected `string` when `tags/combobox` is `true`

Screenshot from 2019-08-29 15-39-07

once I try to click long value field page get blank and get stuck.

### PR DESCRIPTION
**Pull request by ShahAnuj2610**
fixes #333

### CODE REVIEW

File: app/src/utils/mappings.js [hunk 1]
```diff
@@ -8,6 +8,8 @@ const extractColumns = (mappings, key) =>
 
 const META_FIELDS = ['_index', '_type', '_score', '_click_id'];
 
+const NUMBER_FIELDS = ['integer', 'float', 'long', 'double'];
```
Comment (lakhansamani) [inline app/src/utils/mappings.js]: @ShahAnuj2610 minor thing, can we rename this to `NUMERIC_DATATYPES` and add 
remaining numeric types like `short`, `half_float`, etc.
https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html

**Review by lakhansamani — CHANGES_REQUESTED** [review]
